<a href="https://colab.research.google.com/github/bodarynka/pyton-data-analytycs/blob/main/%D0%91%D0%BE%D1%8F%D0%BA%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B0_%22hw_3_2_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%B8_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B8_%D0%B7_%D0%B4%D0%B0%D0%BD%D0%B8%D0%BC%D0%B8_%D1%83_Pandas_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнє завдання до теми "Основи роботи з даними у Pandas"

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [ ]:
import pandas as pd


df = pd.read_csv('/content/supermarket_sales.csv')

1. За допомогою бібліотеки Pandas виведіть перші 4 і останні 4 записи у наборі даних (це дві окремі команди). Треба саме 4! Не 5.

In [ ]:
df.head(4)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4

In [ ]:
df.tail(4)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,3/2/2019,17:16,Ewallet,973.80,4.761905,48.690,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.592,33.432,2/9/2019,13:22,Cash,31.84,4.761905,1.592,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.291,69.111,2/22/2019,15:33,Cash,65.82,4.761905,3.291,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.919,649.299,2/18/2019,13:28,Cash,618.38,4.761905,30.919,6.6

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1F5XlzBOOTMsedpsYqz6NnXjIPTDe6jpx)

2. Виведіть рядки даних з індексами з 615 по 619 включно.

In [ ]:
df.iloc[615:620]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
615,509-29-3912,A,Yangon,Member,Female,Sports and travel,38.72,9,17.4240,365.9040,3/20/2019,12:24,Ewallet,348.48,4.761905,17.4240,4.2
616,327-40-9673,B,Mandalay,Member,Male,Sports and travel,72.60,6,21.7800,457.3800,1/13/2019,19:51,Cash,435.60,4.761905,21.7800,6.9
617,840-19-2096,C,Naypyitaw,Member,Male,Electronic accessories,87.91,5,21.9775,461.5275,3/14/2019,18:10,Ewallet,439.55,4.761905,21.9775,4.4
618,828-46-6863,A,Yangon,Member,Male,Food and beverages,98.53,6,29.5590,620.7390,1/23/2019,11:22,Credit card,591.18,4.761905,29.5590,4.0
619,641-96-3695,C,Naypyitaw,Member,Female,Fashion accessories,43.46,6,13.0380,273.7980,2/7/2019,17:55,Ewallet,260.76,4.761905,13.0380,8.5

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1Otufe_TXRmjZxWigzBiVBLCAVUfEReXM)

3. Виведіть назви колонок у наборі даних разом з їхніми типами. Це можна зробити кількома способами, важливо аби в результаті були назви колонок і відповідні їм типи.

In [ ]:
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

Очікуваний результат (один з можливих форматів):

![](https://drive.google.com/uc?export=view&id=1ASh6-S-_f3X9fTQAPIvnHMFZamTBjNkL)

4. Користуючись методом `DataFrame.describe()` виявіть 1, 25, 50, 75 і 99 персентилі колонки `gross income`. Знайдіть, яке значення відповідає 75отму персентилю цієї колонки і що це означає? Як би Ви його пояснили простими словами колегам? Відповідь напишіть текстом в окремій клітинці типу Markdown.

In [ ]:
df [['gross income']]
display(df.describe(percentiles=[ 0.1, 0.25, 0.5, 0.75, 0.99]))

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
10%,19.313000,1.000000,3.243000,68.103000,64.86000,4.761905,3.243000,4.50000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
99%,99.710200,10.000000,45.250750,950.265750,905.01500,4.761905,45.250750,9.90000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1bDa1YFUWDsPm78Lnpy2geQND8M1HEQiT)

5. Виведіть кількість інвойсів за кожним унікальним містом в наборі даних.

  Підказка: інвойс - це один рядок в цьому наборі даних, ми можемо цим скористатись аби швидко отримати відповідь.

In [ ]:
invoice_count_by_city = df['City'].value_counts()
print(invoice_count_by_city)

City
Yangon       340
Mandalay     332
Naypyitaw    328
Name: count, dtype: int64

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1G8c6M875NOW7oU3OtZegTOnyD2y8lhAV)

6. Виведіть, який відсоток інвойсів припадає на кожне унікальне місто.

In [ ]:
invoice_percentage_by_city = df['City'].value_counts(normalize=True) * 100
print(invoice_percentage_by_city)

City
Yangon       34.0
Mandalay     33.2
Naypyitaw    32.8
Name: proportion, dtype: float64

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1yZZpWhL2y8DX9rSRioYCRh1VbJgcf3fY)

7.1. Використовуючи фільтрацію даних, знайдіть середнє значення `gross income` для міст `Yangon` та `Mandalay`. В якому місті воно більше?

7.2 Сформулюйте 3 гіпотези, чому в одному місті gross income вище, як можна дізнатись чи правдива ця гіпотеза з використанням даних (наявних і додаткових), та як висновки з цих гіпотез можна використати для прийняття рішень як підвищити прибуток в мережі супермаркетів. Відповідь напишіть текстом в окремій клітинці типу Markdown.

Це завдання - на продуктове мислення. Якщо не знаєте, які гіпотези сформулювати - напишіть ті, які здаються вам зовсім примітивними. Важливо навчитись висловлювати свої гіпотези щодо даних, і з часом та досвідом вони будуть ставати щоразу глибше і точніше. Весь аналіз даних будується на тому, що ми перевіряємо певні гіпотези та робимо висновки і рекоемндації на основі своїх досліджень.

In [14]:
# Фільтрація даних для Yangon
yangon_income_mean = df[df['City'] == 'Yangon']['gross income'].mean()

# Фільтрація даних для Mandalay
mandalay_income_mean = df[df['City'] == 'Mandalay']['gross income'].mean()

# Виведення результатів
print(f"Середній дохід у Yangon: {yangon_income_mean:.2f}")
print(f"Середній дохід у Mandalay: {mandalay_income_mean:.2f}")

# Порівняння доходів
if yangon_income_mean > mandalay_income_mean:
    print("У місті Yangon середній дохід більший.")
else:
    print("У місті Mandalay середній дохід більший.")

Середній дохід у Yangon: 14.87
Середній дохід у Mandalay: 15.23
У місті Mandalay середній дохід більший.

Гіпотеза 1: Вищий середній чек
Гіпотеза: В одному з міст (наприклад, у Yangon) середній чек вищий, ніж у Mandalay. Це може бути через те, що в Yangon клієнти частіше купують дорожчі товари або купують більше товарів за один раз.

Як перевірити:

З використанням наявних даних можна обчислити середній чек у кожному місті, порівнявши показник Total у двох містах.
Додатково можна зібрати дані про асортимент товарів у кожному місті, щоб побачити, чи є різниця у наявності більш дорогих товарів.
Як використати:

Якщо виявиться, що в одному з міст середній чек значно вищий, варто переглянути асортимент товарів у інших містах і збільшити частку дорогих товарів.
Також можна провести рекламні кампанії для заохочення клієнтів купувати більше товарів за один раз.
Гіпотеза 2: Вища купівельна спроможність населення
Гіпотеза: У місті з вищим прибутком (наприклад, Yangon) серед клієнтів більше людей з вищою купівельною спроможністю. Це може пояснити вищий рівень продажів і, відповідно, прибутку.

Як перевірити:

З використанням наявних даних можна провести аналіз продажів за категоріями товарів і порівняти середню ціну товарів, які купуються в кожному місті.
Додаткові дані про середній дохід населення в кожному з міст допоможуть підтвердити або спростувати гіпотезу.
Як використати:

Якщо виявиться, що купівельна спроможність в одному місті вища, можна зосередитися на продажах товарів преміум-класу в цьому місті, а в інших містах проводити акції та знижки на більш доступні товари.
Гіпотеза 3: Різні рекламні стратегії
Гіпотеза: У місті з вищим прибутком використовуються ефективніші рекламні стратегії, які залучають більше клієнтів або стимулюють їх купувати більше.

Як перевірити:

На основі наявних даних можна проаналізувати динаміку продажів у різні періоди часу та порівняти, як реклама вплинула на продажі в кожному місті.
Додаткові дані про рекламні бюджети і канали, які використовуються в різних містах, допоможуть визначити ефективність рекламних стратегій.
Як використати:

Якщо виявиться, що рекламні стратегії в одному з міст ефективніші, можна адаптувати ці стратегії для інших міст, щоб підвищити загальний рівень продажів і прибутку в мережі супермаркетів

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1JdXUmK46WcoXUJYP7NS2SJlr2XjBbpQ8)

8. Для продовження дослідження різниці у прибутках в магазинах давайте зʼясуємо, чи відрізняється маржа ('gross margin percentage') для різних інвойсів в магазині? Перевірте це програмно на даних виходячи з того функціоналу, який ми вже пройшли у лекціях.

Дайте на основі отриманого результату відповідь: "У всіх всіх інвойсах однакова маржа" або "Маржа відрізняється для різних інвойсів".

In [15]:
unique_margin_percentages = df['gross margin percentage'].unique()

# Перевірка кількості унікальних значень
if len(unique_margin_percentages) == 1:
    print("У всіх інвойсах однакова маржа")
else:
    print("Маржа відрізняється для різних інвойсів")

У всіх інвойсах однакова маржа

Очікуваний результат: відповідь щодо маржі в усіх інвойсах на основі отриманих результатів

9. Врахуовуючи висновок в попередньому завданні, дослідимо як продаються в цих містах різні категорії товарів. Виведіть відсотковий розпоіділ кількості інвойсів по категоріям товарів `Product line` в містах `Yangon` та `Mandalay`.

In [16]:
df_yangon = df[df['City'] == 'Yangon']
df_mandalay = df[df['City'] == 'Mandalay']

# Відсотковий розподіл кількості інвойсів по категоріям товарів для Yangon
yangon_product_line_distribution = df_yangon['Product line'].value_counts(normalize=True) * 100

# Відсотковий розподіл кількості інвойсів по категоріям товарів для Mandalay
mandalay_product_line_distribution = df_mandalay['Product line'].value_counts(normalize=True) * 100

# Виведення результатів
print("Відсотковий розподіл кількості інвойсів по категоріям товарів у місті Yangon:")
print(yangon_product_line_distribution)
print("\nВідсотковий розподіл кількості інвойсів по категоріям товарів у місті Mandalay:")
print(mandalay_product_line_distribution)

Відсотковий розподіл кількості інвойсів по категоріям товарів у місті Yangon:
Product line
Home and lifestyle        19.117647
Electronic accessories    17.647059
Sports and travel         17.352941
Food and beverages        17.058824
Fashion accessories       15.000000
Health and beauty         13.823529
Name: proportion, dtype: float64

Відсотковий розподіл кількості інвойсів по категоріям товарів у місті Mandalay:
Product line
Fashion accessories       18.674699
Sports and travel         18.674699
Electronic accessories    16.566265
Health and beauty         15.963855
Food and beverages        15.060241
Home and lifestyle        15.060241
Name: proportion, dtype: float64

Очікуваний результат для кожного з міст:

![](https://drive.google.com/uc?export=view&id=1IbG58YK5KVqC-wCnllF1btgEgfWTbi_O)

![](https://drive.google.com/uc?export=view&id=1aKOkLmlMq1sOh4GbwyaQyjfhNJzdU4Yh)